# Armour Affixes - Minimal set showing defense and utility

# PREFIXES

[[affixes]]
id = "added_life"
name = "Robust"
type = "prefix"
stat = "added_life"
scope = "global"
tags = ["life", "defense"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 100
min = 80
max = 100
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 300
min = 50
max = 79
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 600
min = 25
max = 49
min_ilvl = 1

[[affixes]]
id = "increased_armour"
name = "Reinforced"
type = "prefix"
stat = "increased_armour"
scope = "global"
tags = ["armour", "defense"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 150
min = 70
max = 100
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 400
min = 40
max = 69
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 800
min = 15
max = 39
min_ilvl = 1

[[affixes]]
id = "increased_evasion"
name = "Agile"
type = "prefix"
stat = "increased_evasion"
scope = "global"
tags = ["evasion", "defense"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 150
min = 70
max = 100
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 400
min = 40
max = 69
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 800
min = 15
max = 39
min_ilvl = 1

[[affixes]]
id = "increased_energy_shield"
name = "Shimmering"
type = "prefix"
stat = "increased_energy_shield"
scope = "global"
tags = ["energy_shield", "defense", "caster"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 150
min = 70
max = 100
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 400
min = 40
max = 69
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 800
min = 15
max = 39
min_ilvl = 1

# SUFFIXES

[[affixes]]
id = "fire_resistance"
name = "of the Salamander"
type = "suffix"
stat = "fire_resistance"
scope = "global"
tags = ["fire", "resistance", "defense"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 150
min = 36
max = 45
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 400
min = 24
max = 35
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 800
min = 12
max = 23
min_ilvl = 1

[[affixes]]
id = "cold_resistance"
name = "of the Penguin"
type = "suffix"
stat = "cold_resistance"
scope = "global"
tags = ["cold", "resistance", "defense"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 150
min = 36
max = 45
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 400
min = 24
max = 35
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 800
min = 12
max = 23
min_ilvl = 1

[[affixes]]
id = "lightning_resistance"
name = "of Grounding"
type = "suffix"
stat = "lightning_resistance"
scope = "global"
tags = ["lightning", "resistance", "defense"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 150
min = 36
max = 45
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 400
min = 24
max = 35
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 800
min = 12
max = 23
min_ilvl = 1

[[affixes]]
id = "added_strength"
name = "of the Bear"
type = "suffix"
stat = "added_strength"
scope = "global"
tags = ["strength", "attribute"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 200
min = 35
max = 50
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 500
min = 20
max = 34
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 1000
min = 8
max = 19
min_ilvl = 1

[[affixes]]
id = "added_dexterity"
name = "of the Cat"
type = "suffix"
stat = "added_dexterity"
scope = "global"
tags = ["dexterity", "attribute"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 200
min = 35
max = 50
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 500
min = 20
max = 34
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 1000
min = 8
max = 19
min_ilvl = 1

[[affixes]]
id = "added_intelligence"
name = "of the Owl"
type = "suffix"
stat = "added_intelligence"
scope = "global"
tags = ["intelligence", "attribute", "caster"]
allowed_classes = ["helmet", "body_armour", "gloves", "boots", "shield"]

[[affixes.tiers]]
tier = 1
weight = 200
min = 35
max = 50
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 500
min = 20
max = 34
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 1000
min = 8
max = 19
min_ilvl = 1

[[affixes]]
id = "increased_movement_speed"
name = "of Haste"
type = "suffix"
stat = "increased_movement_speed"
scope = "global"
tags = ["speed", "utility"]
allowed_classes = ["boots"]

[[affixes.tiers]]
tier = 1
weight = 100
min = 25
max = 30
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 300
min = 15
max = 24
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 600
min = 8
max = 14
min_ilvl = 1

# Block & Dodge

[[affixes]]
id = "block_chance"
name = "Warding"
type = "prefix"
stat = "block_chance"
scope = "global"
tags = ["block", "defense"]
allowed_classes = ["shield"]

[[affixes.tiers]]
tier = 1
weight = 100
min = 6
max = 8
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 300
min = 3
max = 5
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 600
min = 1
max = 2
min_ilvl = 1

[[affixes]]
id = "block_amount"
name = "Bulwark"
type = "prefix"
stat = "block_amount"
scope = "global"
tags = ["block", "defense"]
allowed_classes = ["shield"]

[[affixes.tiers]]
tier = 1
weight = 100
min = 40
max = 60
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 300
min = 20
max = 39
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 600
min = 8
max = 19
min_ilvl = 1

[[affixes]]
id = "spell_dodge_chance"
name = "of Spell Evasion"
type = "suffix"
stat = "spell_dodge_chance"
scope = "global"
tags = ["dodge", "caster", "defense"]
allowed_classes = ["boots", "body_armour"]

[[affixes.tiers]]
tier = 1
weight = 80
min = 5
max = 8
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 200
min = 3
max = 4
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 500
min = 1
max = 2
min_ilvl = 1

# Damage Reduction

[[affixes]]
id = "physical_damage_reduction"
name = "of Fortitude"
type = "suffix"
stat = "physical_damage_reduction"
scope = "global"
tags = ["physical", "defense"]
allowed_classes = ["shield", "body_armour"]

[[affixes.tiers]]
tier = 1
weight = 60
min = 4
max = 6
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 150
min = 2
max = 3
min_ilvl = 25

[[affixes.tiers]]
tier = 3
weight = 400
min = 1
max = 1
min_ilvl = 1

[[affixes]]
id = "reduced_damage_taken"
name = "Indomitable"
type = "prefix"
stat = "reduced_damage_taken"
scope = "global"
tags = ["defense"]
allowed_classes = ["body_armour"]

[[affixes.tiers]]
tier = 1
weight = 30
min = 3
max = 5
min_ilvl = 50

[[affixes.tiers]]
tier = 2
weight = 80
min = 1
max = 2
min_ilvl = 25
