[table]
id = "boss"

[[table.rolls]]
count = 3
weight = 30

[[table.rolls]]
count = 4
weight = 50

[[table.rolls]]
count = 5
weight = 20

[[entries]]
type = "no_drop"
weight = 20

[[entries]]
type = "item"
base_type = "plate_vest"
currencies = ["alchemy"]
weight = 15
rarity_bonus = 30
min_level = 10

[[entries]]
type = "item"
base_type = "crystal_wand"
currencies = ["alchemy", "exalt"]
weight = 10
rarity_bonus = 40
min_level = 20

[[entries]]
type = "unique"
id = "titans_grip"
weight = 1
rarity_bonus = 10
min_level = 5

[[entries]]
type = "currency"
id = "chaos"
count = [1, 3]
weight = 20

[[entries]]
type = "currency"
id = "alchemy"
count = [1, 2]
weight = 25

[[entries]]
type = "currency"
id = "regal"
count = 1
weight = 15
rarity_bonus = 5

[[entries]]
type = "table"
id = "gems_common"
weight = 25
